--create database Khmer_Event
--create table tblKhmerEvent(
--  EventID int IDENTITY(1,1) primary key,
--  EventName nvarchar(200),
--  Douration nvarchar(100),
--  DateStart nvarchar(100),
--  DateEnd nvarchar(100),
--  Price money,
--  Place nvarchar(100),
--  [Description] nvarchar(max),
--  Contace nvarchar(200),
--  Link nvarchar(max),
--  ImageURL nvarchar(200),
--  Username nvarchar(200),
--);